//SOLVE FOR ACTIVITY 2

//A
SELECT E.LNAME, E.FNAME
FROM EMPLOYEE E, EMPLOYEE S
WHERE S.FNAME='Franklin' AND S.LNAME='Wong' AND E.SUPERSSN=S.SSN;

//B
SELECT LNAME, FNAME FROM EMPLOYEE, DEPENDENT 
WHERE sex='F' AND SSN=ESSN AND FNAME=DEPENDENT_NAME;

//C

SELECT Last_Name, Hire_Date ,Manager_id
FROM emps

//D
SELECT FNAME, LNAME, PNAME, HOURS, DNAME
FROM employee,department,works_on,project
